<?php
/**
 * Created by PhpStorm.
 * User: Ondřej
 * Date: 29.06.2016
 * Time: 17:29
 */?>
<h1>Přihlášení do administrace - Login to administration</h1>

<form method="post">
    Jméno - username<br />
    <input type="text" name="username" /><br />
    Heslo - password<br />
    <input type="password" name="password" /><br />
    <input type="submit" value="Přihlásit" />
</form>

<p>Pokud ještě nemáte účet, <a href="registrace">zaregistrujte se</a> - <a href="registrace">Don't have an account?</a></p>
