<?php
/**
 * Created by PhpStorm.
 * User: Ondřej
 * Date: 29.06.2016
 * Time: 17:06
 */?>
<h1>Registrace - Register</h1>

<form method="post">
    Jméno - username<br />
    <input type="text" name="name" /><br />
    Heslo - password<br />
    <input type="password" name="password" /><br />
    Heslo znovu - password again<br />
    <input type="password" name="password_again" /><br />
    Zadejte aktuální rok  - type actual year(antispam)<br />
    <input type="text" name="year" /><br />
    <input type="submit" value="Registrovat" />
</form>
