<?php
/**
 * Created by PhpStorm.
 * User: Ondřej
 * Date: 24.06.2016
 * Time: 23:24
 */
?>
<!doctype html>
<!--
If you are rly carageous and reading this web, plz dont say I'm cruel right?
Cuz I'm not cruel I'm just lazy to write readable code. Thanks :-).
-->
    <html>
        <!--  #ff7d01  -->
        <head>
            <base href="/dameparbu.cz" />

            <title><?= $title ?></title>

            <meta charset="UTF-8">
            <meta name="description" content="<?= $description ?>" />
            <meta name="keywords" content="<?= $keywords ?>" />
            <!-- Android, Firefox OS - Chrome, Opera, Vivaldi -->
            <meta name="theme-color" content="#163038" />
            <!-- Bullshit that names Windows Phone  -->
            <meta name="msapplication-navbutton-color" content="#163038" />
            <!-- Godness names Apple - iOS -->
            <meta name="apple-mobile-web-app-capable" content="yes">
            <meta name="apple-mobile-web-app-status-bar-style" content="#163038"/>

            <link rel="stylesheet" type="text/css" href="../design/CSS/style.css">
            <link rel="shourtcut icon" href="../design/images/favico.png">
            <link href='https://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
            <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
            <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
            <script src="../design/JS/ShowAndDismiss.js"></script>
            <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        </head>
        <body>
            <header>
                <div class="top-top">
                    <?php foreach($errorMessages as $errorMessage): ?>
                        <div class="errorMessage <?= $errorMessage['type'] ?>"><?= $errorMessage['error_message'] ?></div>
                    <?php endforeach; ?>
                </div>
                <div style="position: relative; width: 100%; height: 100%; " id="myCarousel" class="carousel slide" data-ride="carousel">

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img style="position: relative; max-height: 320px;" height="320px">
                            <div class="carousel-caption">
                                <span class="border">
                                    <h3>Android chystá revoluci mobilních her</h3>
                                    <p>Vývojáři operačního systému Android pro mobilní zařízení chystá obrat ve světě mobilních her...</p>
                                </span>
                            </div>
                        </div>

                    </div>

                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </header>
            <div class="top">
                <ul class="menu">
                    <li style="font-size: 20px;">
                        <a href="?pages=index">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                        </a>
                    </li>
                    <li><a href="?pages=novinky">Novinky</a></li>
                    <li><a href="?pages=clanky">Články</a></li>
                    <li><a href="?pages=recenze">Recenze</a></li>
                    <li><a href="?pages=komunita">Komunita</a></li>
                </ul>
                <div class="social">
                    <a href=""><img src="images/youtube-icon.png" class="round-img" height="40px"></a> <a href="http://facebook.com/dameparbu.cz" target="_blank"><img class="round-img" src="images/facebook_icon.png" height="40px">
                    </a>
                </div>
                <div class="account">
                    <img style=" border: 2px solid #cf0b0b; left: 10px; position: relative;" class="img-circle" width="50px" src="images/login.png">
                    <span class="nick">Přihlásit</span>
                    <span class="descript">Popis či něco jiného</span>
                    <span class="arrow"><span class="glyphicon glyphicon-chevron-down" id="show" onclick="ShowAndDimiss('click')" aria-hidden="true"></span></span>
                    <div id="click">
                        <span class="login">Přihlásit se</span>
                        <span class="register">Registrace</span>
                    </div>
                </div></div>
            </div>
            <div class="content">
            <?php
                $this->kontroler->vypisPohled();
            ?>
            </div>
            <footer>
                <div class="live-menu">
                    <a href="section/contact">Kontakt</a>
                </div>
                <div class="live-menu">
                    <a  href="section/about-us">O nás</a>
                </div>
                <div class="live-menu">
                    <a  href="section/team">Tým</a>
                </div>
                <p>DámePařbu.cz | Všechna práva vyhrazena.</p>
            </footer>
        </body>
    </html>